### ISSUE TITLE
Unknown rotationSpeed

### ISSUE THREAD

**Issue by jadonbaker** [tasict/homebridge-daikin-local-platform#2]
Thanks for your effort updating this plugin to support the new API structure.
I'm noticing the following logs:
```
[22/01/2024, 06:45:21] [Daikin Local Platform] Unknown RotationSpeed
[22/01/2024, 06:45:21] [Daikin Local Platform] 6
```
It appears either the device I'm using has an additional rotation speed or it is incorrectly being set from somewhere. Let me know if I can assist any further with debugging.

**Comment by tasict** [comment]
I understand the issue with the air conditioning API for Daikin air conditioners regarding the fan speed settings in different modes. It's a bit troublesome. Unfortunately, I currently don't have the free time to address this matter. If you are willing to assist in handling this, you are very welcome to create a pull request directly.

**Comment by jadonbaker** [comment]
I have not seen this issue again after updating to latest version.

**Comment by jadonbaker** [comment]
I have not seen this issue again after updating to latest version.
