### ISSUE TITLE
Not response in Homekit

### ISSUE THREAD

**Issue by hank418** [tasict/homebridge-daikin-local-platform#3]
It's work in homebridge, but shows not response in Homekit.
![IMG_8697](https://github.com/tasict/homebridge-daikin-local-platform/assets/2628006/337c7aaa-4382-49f9-8982-cc9a73fd3591)

**Comment by tasict** [comment]
Normally, if the Homebridge web interface is normal but the Home App does not respond, the possibility of a problem with the plugin is relatively small.

In my experience, you need to confirm the stability of the WiFi connection for the home hub Apple TV/HomePod/Homebridge Host.

**Comment by hank418** [comment]
After I reboot home hub it's work now. Thanks a lot.

**Comment by tasict** [comment]
@hank418 I suggest that you use Subbridge for more time-consuming plugins, such as those that require communication. In my experience, this can reduce the response time of the Home App.

**Comment by hank418** [comment]
Sounds great! Thanks your recommadation.
