### ISSUE TITLE
I need more option

### ISSUE THREAD

**Issue by chen441990** [tasict/homebridge-daikin-local-platform#4]
When I turn on AC, I need defaultMode is cooling. Can u add this option in plugin???

**Comment by tasict** [comment]
Ok, I will add it.

**Comment by chen441990** [comment]
Hey you, do u have free time to add them? Please help me

**Comment by tasict** [comment]
What option?

**Comment by tasict** [comment]
@chen441990 After trying to implement it, I found that adding the default mode causes the commands sent by Siri to become confused. Therefore, I suggest you use commands to instruct Siri, such as "Siri, set xx air conditioner to cooling mode."
